/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senandika.UILayer.Autentikasi;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import javax.swing.JOptionPane;
import senandika.ServiceLayer.AuthService;
import senandika.ServiceLayer.Session;
import senandika.UILayer.Autentikasi.Login;


public class ForgotPassword extends javax.swing.JFrame {

    private boolean passwordVisible = false;
    public ForgotPassword() {
        initComponents();
        setupPasswordPlaceholder();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slide1 = new javax.swing.JPanel();
        confirmNewPw = new javax.swing.JPasswordField();
        hintNewConfirmPw = new javax.swing.JButton();
        inputNewPw = new javax.swing.JPasswordField();
        hintNewPw = new javax.swing.JButton();
        btnFogotPw = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slide1.setBackground(new java.awt.Color(246, 255, 248));
        Slide1.setPreferredSize(new java.awt.Dimension(816, 546));
        Slide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmNewPw.setBackground(new java.awt.Color(246, 255, 248));
        confirmNewPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        confirmNewPw.setText("jPasswordField1");
        confirmNewPw.setBorder(null);
        confirmNewPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewPwActionPerformed(evt);
            }
        });
        Slide1.add(confirmNewPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, 30));

        hintNewConfirmPw.setBackground(new java.awt.Color(255, 255, 248));
        hintNewConfirmPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/component/eyePassword/hintPassword.png"))); // NOI18N
        hintNewConfirmPw.setBorder(null);
        hintNewConfirmPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintNewConfirmPwActionPerformed(evt);
            }
        });
        Slide1.add(hintNewConfirmPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        inputNewPw.setBackground(new java.awt.Color(246, 255, 248));
        inputNewPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputNewPw.setText("jPasswordField1");
        inputNewPw.setBorder(null);
        inputNewPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewPwActionPerformed(evt);
            }
        });
        Slide1.add(inputNewPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 230, 30));

        hintNewPw.setBackground(new java.awt.Color(255, 255, 248));
        hintNewPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/component/eyePassword/hintPassword.png"))); // NOI18N
        hintNewPw.setBorder(null);
        hintNewPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintNewPwActionPerformed(evt);
            }
        });
        Slide1.add(hintNewPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        btnFogotPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFogotPwMouseClicked(evt);
            }
        });
        Slide1.add(btnFogotPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 290, 50));

        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        Slide1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 70, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/halaman/autentikasi/Forgot Password .png"))); // NOI18N
        Slide1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmNewPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmNewPwActionPerformed

    private void hintNewConfirmPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintNewConfirmPwActionPerformed
        if (passwordVisible) {

            confirmNewPw.setEchoChar('•');

            passwordVisible = false;

        } else {

            confirmNewPw.setEchoChar((char) 0);

            passwordVisible = true;

        }
    }//GEN-LAST:event_hintNewConfirmPwActionPerformed

    private void btnFogotPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFogotPwMouseClicked
    String password =
            new String(inputNewPw.getPassword());

    String confirmPassword =
            new String(confirmNewPw.getPassword());

    // VALIDASI
    if (password.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Password baru tidak boleh kosong!"
        );

        return;
    }

    if (password.length() < 6) {

        JOptionPane.showMessageDialog(
                this,
                "Password minimal 6 karakter!"
        );

        return;
    }

    if (!password.equals(confirmPassword)) {

        JOptionPane.showMessageDialog(
                this,
                "Konfirmasi password tidak cocok!"
        );

        return;
    }

    try {

        AuthService authService =
                new AuthService();

        String response =
                authService.resetPassword(
                        Session.RESET_EMAIL,
                        password
                );

        JsonObject jsonObject =
                JsonParser.parseString(response)
                        .getAsJsonObject();

        boolean success =
                jsonObject.get("success")
                        .getAsBoolean();

        String message =
                jsonObject.get("message")
                        .getAsString();

        if (success) {

            JOptionPane.showMessageDialog(
                    this,
                    message,
                    "Berhasil",
                    JOptionPane.INFORMATION_MESSAGE
            );

            Login login = new Login();

            login.setVisible(true);

            this.dispose();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    message,
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_btnFogotPwMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        Login signin = new Login();
        signin.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void inputNewPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewPwActionPerformed

    private void hintNewPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintNewPwActionPerformed
        if (passwordVisible) {

            inputNewPw.setEchoChar('•');

            passwordVisible = false;

        } else {

            inputNewPw.setEchoChar((char) 0);

            passwordVisible = true;

        }
    }//GEN-LAST:event_hintNewPwActionPerformed

    private void setupPasswordPlaceholder() {
        inputNewPw.setText("Masukkan password baru"); 
        confirmNewPw.setText("Konfirmasi password anda"); 

        inputNewPw.setEchoChar((char) 0);
        confirmNewPw.setEchoChar((char) 0);

        inputNewPw.addFocusListener(new java.awt.event.FocusAdapter() {

            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {

                String password =
                        String.valueOf(inputNewPw.getPassword());

                if (password.equals("Masukkan password baru")) {

                    inputNewPw.setText("");

                    inputNewPw.setEchoChar('•');
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {

                String password =
                        String.valueOf(inputNewPw.getPassword());

                if (password.isEmpty()) {

                    inputNewPw.setText("Masukkan password baru");

                    inputNewPw.setEchoChar((char) 0);
                }
            }
        });
        
        confirmNewPw.addFocusListener(new java.awt.event.FocusAdapter() {

            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {

                String password =
                        String.valueOf(confirmNewPw.getPassword());

                if (password.equals("Konfirmasi password anda")) {

                    confirmNewPw.setText("");

                    confirmNewPw.setEchoChar('•');
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {

                String password =
                        String.valueOf(confirmNewPw.getPassword());

                if (password.isEmpty()) {

                    confirmNewPw.setText("Konfirmasi password anda");
                    confirmNewPw.setEchoChar((char) 0);
                }
            }
        });
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Slide1;
    private javax.swing.JLabel btnFogotPw;
    private javax.swing.JLabel cancel;
    private javax.swing.JPasswordField confirmNewPw;
    private javax.swing.JButton hintNewConfirmPw;
    private javax.swing.JButton hintNewPw;
    private javax.swing.JPasswordField inputNewPw;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
