/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senandika.UILayer.Autentikasi;

import senandika.UILayer.Autentikasi.Register;

/**
 *
 * @author SAHABAT-IT
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Slide1 = new javax.swing.JPanel();
        inputEmail = new javax.swing.JTextField();
        inputPw = new javax.swing.JPasswordField();
        hintPw = new javax.swing.JButton();
        btnLogin = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        forgotPw1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slide1.setBackground(new java.awt.Color(246, 255, 248));
        Slide1.setPreferredSize(new java.awt.Dimension(816, 546));
        Slide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputEmail.setBackground(new java.awt.Color(246, 255, 248));
        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputEmail.setText("Masukkan Email");
        inputEmail.setBorder(null);
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        Slide1.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 260, 30));

        inputPw.setBackground(new java.awt.Color(246, 255, 248));
        inputPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputPw.setText("jPasswordField1");
        inputPw.setBorder(null);
        inputPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPwActionPerformed(evt);
            }
        });
        Slide1.add(inputPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 230, 30));

        hintPw.setBackground(new java.awt.Color(255, 255, 248));
        hintPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hintPassword.png"))); // NOI18N
        hintPw.setBorder(null);
        hintPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintPwActionPerformed(evt);
            }
        });
        Slide1.add(hintPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        Slide1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 290, 50));

        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        Slide1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, 20));

        forgotPw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPw1MouseClicked(evt);
            }
        });
        Slide1.add(forgotPw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 120, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Login.png"))); // NOI18N
        Slide1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void inputPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPwActionPerformed

    private void hintPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintPwActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        Register signup = new Register();
        signup.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerMouseClicked

    private void forgotPw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPw1MouseClicked
        ForgotPassword lupaPw = new ForgotPassword();
        lupaPw.setVisible(true);
        dispose();
    }//GEN-LAST:event_forgotPw1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Slide1;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel forgotPw1;
    private javax.swing.JButton hintPw;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPasswordField inputPw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel register;
    // End of variables declaration//GEN-END:variables
}
