/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senandika.UILayer;

/**
 *
 * @author SAHABAT-IT
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slide1 = new javax.swing.JPanel();
        inputEmail = new javax.swing.JTextField();
        createPw = new javax.swing.JPasswordField();
        hintCreatePw = new javax.swing.JButton();
        btnRegister = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        confirmPw = new javax.swing.JPasswordField();
        hintConfirmPw = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slide1.setBackground(new java.awt.Color(246, 255, 248));
        Slide1.setPreferredSize(new java.awt.Dimension(816, 546));
        Slide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputEmail.setBackground(new java.awt.Color(246, 255, 248));
        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputEmail.setText("Masukkan Email");
        inputEmail.setBorder(null);
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        Slide1.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 260, 30));

        createPw.setBackground(new java.awt.Color(246, 255, 248));
        createPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        createPw.setText("jPasswordField1");
        createPw.setBorder(null);
        createPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPwActionPerformed(evt);
            }
        });
        Slide1.add(createPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 230, 30));

        hintCreatePw.setBackground(new java.awt.Color(255, 255, 248));
        hintCreatePw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hintPassword.png"))); // NOI18N
        hintCreatePw.setBorder(null);
        hintCreatePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintCreatePwActionPerformed(evt);
            }
        });
        Slide1.add(hintCreatePw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        Slide1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 290, 50));

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        Slide1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 50, 20));

        confirmPw.setBackground(new java.awt.Color(246, 255, 248));
        confirmPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        confirmPw.setText("jPasswordField1");
        confirmPw.setBorder(null);
        confirmPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPwActionPerformed(evt);
            }
        });
        Slide1.add(confirmPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 230, 30));

        hintConfirmPw.setBackground(new java.awt.Color(255, 255, 248));
        hintConfirmPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hintPassword.png"))); // NOI18N
        hintConfirmPw.setBorder(null);
        hintConfirmPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintConfirmPwActionPerformed(evt);
            }
        });
        Slide1.add(hintConfirmPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Register.png"))); // NOI18N
        Slide1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void createPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPwActionPerformed

    private void hintCreatePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintCreatePwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintCreatePwActionPerformed

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        Login signin = new Login();
        signin.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginMouseClicked

    private void confirmPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPwActionPerformed

    private void hintConfirmPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintConfirmPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintConfirmPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Slide1;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JPasswordField confirmPw;
    private javax.swing.JPasswordField createPw;
    private javax.swing.JButton hintConfirmPw;
    private javax.swing.JButton hintCreatePw;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel login;
    // End of variables declaration//GEN-END:variables
}
