/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senandika.UILayer;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import javax.swing.JOptionPane;
import senandika.ServiceLayer.ProfileService;

/**
 *
 * @author SAHABAT-IT
 */
public class UpdateProfile extends javax.swing.JFrame {

    private final String BASE_URL =
        "http://localhost:5000";
    public UpdateProfile() {
        initComponents();
        loadProfile();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slide3 = new javax.swing.JPanel();
        btnStartnow = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        inputUsername = new javax.swing.JTextField();
        inputFullName = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        cbStress = new javax.swing.JComboBox<>();
        cbActivity = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slide3.setBackground(new java.awt.Color(246, 255, 248));
        Slide3.setPreferredSize(new java.awt.Dimension(816, 546));
        Slide3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStartnow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartnowMouseClicked(evt);
            }
        });
        Slide3.add(btnStartnow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 230, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Update Profile");
        Slide3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        btnSimpan.setText("Simpan Perubahan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        Slide3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        Slide3.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        inputUsername.setBackground(new java.awt.Color(246, 255, 248));
        inputUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputUsername.setBorder(javax.swing.BorderFactory.createTitledBorder("Full Name"));
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        Slide3.add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 250, 50));

        inputFullName.setBackground(new java.awt.Color(246, 255, 248));
        inputFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputFullName.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        inputFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFullNameActionPerformed(evt);
            }
        });
        Slide3.add(inputFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 250, 50));

        cbGender.setBackground(new java.awt.Color(246, 255, 248));
        cbGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Laki-Laki", "Perempuan", " " }));
        cbGender.setBorder(javax.swing.BorderFactory.createTitledBorder("Gender"));
        cbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderActionPerformed(evt);
            }
        });
        Slide3.add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 250, 50));

        cbStress.setBackground(new java.awt.Color(246, 255, 248));
        cbStress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbStress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Sangat Santai", "Santai", "Normal", "Stres", "Sangat Stres", " " }));
        cbStress.setBorder(javax.swing.BorderFactory.createTitledBorder("Stres"));
        cbStress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStressActionPerformed(evt);
            }
        });
        Slide3.add(cbStress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 250, 50));

        cbActivity.setBackground(new java.awt.Color(246, 255, 248));
        cbActivity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbActivity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Mendengarkan musik", "Olahraga", "Menonton film", "Bermain game", "Membaca buku", "Meditasi", "Jalan-jalan", " " }));
        cbActivity.setBorder(javax.swing.BorderFactory.createTitledBorder("Aktivitas"));
        cbActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActivityActionPerformed(evt);
            }
        });
        Slide3.add(cbActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Slide3, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Slide3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartnowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartnowMouseClicked
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStartnowMouseClicked

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void inputFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFullNameActionPerformed

    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderActionPerformed

    private void cbStressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStressActionPerformed

    private void cbActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActivityActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {

            String username =
                    inputUsername.getText();

            String fullName =
                    inputFullName.getText();

            String gender =
                    cbGender
                    .getSelectedItem()
                    .toString();

            String stressText =
                    cbStress
                    .getSelectedItem()
                    .toString();

            int stressLevel =
                    convertStressLevel(stressText);

            String activity =
                    cbActivity
                    .getSelectedItem()
                    .toString();

            ProfileService service =
                    new ProfileService();

            String response =
                    service.updateProfile(
                            username,
                            fullName,
                            gender,
                            stressLevel,
                            activity
                    );

            JOptionPane.showMessageDialog(
                    this,
                    "Profile berhasil diperbarui"
            );
            
            Profile profil = new Profile();
            profil.setVisible(true);
            dispose();
            System.out.println(response);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        Profile profil = new Profile();
        profil.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private int convertStressLevel(
        String level
    ) {

        switch (level) {

            case "Sangat Santai":
                return 1;

            case "Santai":
                return 2;

            case "Normal":
                return 3;

            case "Stres":
                return 4;

            case "Sangat Stres":
                return 5;

            default:
                return 3;
        }
    }
    
    private void loadProfile() {
      
        try {
            ProfileService service =
                    new ProfileService();

            String response =
                    service.getProfile();

            JsonObject json =
                    JsonParser
                    .parseString(response)
                    .getAsJsonObject();

            JsonObject data =
                    json.getAsJsonObject("data");

            inputUsername.setText(
                    data.get("username")
                    .getAsString()
            );

            inputFullName.setText(
                    data.get("full_name")
                    .getAsString()
            );

            cbGender.setSelectedItem(
                    data.get("gender")
                    .getAsString()
            );

            int stressLevel =
                    data.get("stress_level")
                    .getAsInt();

            switch (stressLevel) {

                case 1:
                    cbStress.setSelectedItem(
                            "Sangat Santai"
                    );
                    break;

                case 2:
                    cbStress.setSelectedItem(
                            "Santai"
                    );
                    break;

                case 3:
                    cbStress.setSelectedItem(
                            "Normal"
                    );
                    break;

                case 4:
                    cbStress.setSelectedItem(
                            "Stres"
                    );
                    break;

                case 5:
                    cbStress.setSelectedItem(
                            "Sangat Stres"
                    );
                    break;
            }

            cbActivity.setSelectedItem(
                    data.get("favorite_activity")
                    .getAsString()
            );

          }catch (Exception e) {

                JOptionPane.showMessageDialog(
                        this,
                        e.getMessage()
                );
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Slide3;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel btnStartnow;
    private javax.swing.JComboBox<String> cbActivity;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbStress;
    private javax.swing.JTextField inputFullName;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
