/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senandika.UILayer;

import javax.swing.Timer;

/**
 *
 * @author SAHABAT-IT
 */
public class WelcomeScreen2 extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen2() {
        initComponents();
        setLocationRelativeTo(null);
        Timer timer = new Timer(5000, e -> {
                WelcomeScreen3 wScreen3 = new WelcomeScreen3();
                wScreen3.setVisible(true);
                dispose();
        });

        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slide1 = new javax.swing.JPanel();
        NextSlide3 = new javax.swing.JLabel();
        PreviousSlide1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slide1.setBackground(new java.awt.Color(246, 255, 248));
        Slide1.setPreferredSize(new java.awt.Dimension(816, 546));
        Slide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextSlide3.setText("                    ");
        NextSlide3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextSlide3MouseClicked(evt);
            }
        });
        Slide1.add(NextSlide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 80, 20));

        PreviousSlide1.setText("                    ");
        PreviousSlide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreviousSlide1MouseClicked(evt);
            }
        });
        Slide1.add(PreviousSlide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 80, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/WelcomeFlow2.png"))); // NOI18N
        Slide1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousSlide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousSlide1MouseClicked
        dispose();
        WelcomeScreen Screen1 = new WelcomeScreen();
        Screen1.setVisible(true);
    }//GEN-LAST:event_PreviousSlide1MouseClicked

    private void NextSlide3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextSlide3MouseClicked
        dispose();
        WelcomeScreen3 Screen3 = new WelcomeScreen3();
        Screen3.setVisible(true);
    }//GEN-LAST:event_NextSlide3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NextSlide3;
    private javax.swing.JLabel PreviousSlide1;
    private javax.swing.JPanel Slide1;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
